### ISSUE TITLE
Active ?

### ISSUE THREAD

**Issue by spacecabbie** [otacke/h5p-timer#4]
Hi is this project still actieve ? 
Ifso is there maybe a bit more documentation how to implent this ?

**Comment by otacke** [comment]
Sure. Have you checked the readme thoroughly?

**Comment by spacecabbie** [comment]
I did but before i can access the api these files have to be placed somewhere i presume and i was wondering where that is ?

**Comment by otacke** [comment]
As always in H5P, you define a library dependency in library.json and then you'll just have to create an instance of an H5P.Timer class inside your code.

If you need a reference as an example, you can check memory game. https://github.com/h5p/h5p-memory-game (although it has some middle component in between the game itself and the timer).

**Comment by spacecabbie** [comment]
Yep that cleared allot up got it semi working i was tryíng to add it to the quiz module got quite far thanks to your explaination but it looks like to much programming for me i'll get a programmer involved.

Thanks so much for answering my perhaps dumb question but it helped me to understand how it works !
The think that was not quite clear to me was i just had to call the timer.js from within the h5p module liberary. and then edit the main programm.js but its quite complex. Neverteless this module allows me to save a bit on programming !

**Comment by otacke** [comment]
You can find more information about how to use libraries with H5P at https://h5p.org/library-definition. By adding the dependency to library.json you basically tell H5P to load that librarys "preloadedJs" scripts as if you'd add them to an HTML page using `<script src="myfile.js" />`. In the case of H5P.Timer, you'll then just have to create a new object with the parameters that you need as shown in the API's examples.

p. s.: Of course, by setting the preloadedJs directly to any JavaScript file (regardless of being part of H5P or not), you can load that as well. This allows you to use existing stuff that was intended for other purposes as well.

**Comment by spacecabbie** [comment]
Hi if i may can i pick your brain a bit more. I am learning this as i go so sorry if they are really really stupid questions :)

So have installed the h5p file its in the library lists (content - > H5P Libraries -> upload)  (note i use opigno dist).

So now i edited library.json (in the h5p liberary -> sites/default/files/h5p/libraries/H5P.QuestionSet-1.15/library.json (the file code is included below)

So this will not load the timer i have tested several ways (guided by a professional coder)
We tested in console and we cannot see or call on the h5p.timer

We ended up to safe time to "hack it" i placed the whole timer.js code on top of questionere.js and made the code changes to call and start the timer. Tt works perfectly (need some fine tuning of-course but i am a beginner afterall)

So my questions are:
1. How do i get the h5p.timer loaded in the questionnaire, Did I do it correctly as i described and maybe opigno is preventing it from loaded ? Or did i forget something or ?
2. I have added code to questionnaire for the timer when i update this code will be overwritten what is the correct way to insert the code so it will remain when updated. Create my own h5p module ? or just manually add the code every time ? or can i perhaps call the new code just like h5p.timer.js is called ?
3. The code to call and start the time is in the end quite basic so thats cool i was just wondering why is this not suited for timesentive applications ?

I happy to hear any suggestions or tips i have updated this issue since its not realy an issue and din't want open an unnecery issue i hope can help me out.

This is how i edited it.

`{
  "title": "Question Set",
  "description": "Put together a set of different questions that has to be solved. (Quiz)",
  "contentType": "question",
  "majorVersion": 1,
  "minorVersion": 15,
  "patchVersion": 3,
  "embedTypes": [
    "iframe"
  ],
  "runnable": 1,
  "fullscreen": 0,
  "machineName": "H5P.QuestionSet",
  "author": "Joubel",
  "coreApi": {
    "majorVersion": 1,
    "minorVersion": 14
  },
  "license": "MIT",
  "preloadedJs": [
    {
      "path": "js/questionset.js"
    }
  ],
  "preloadedCss": [
    {
      "path": "css/questionset.css"
    }
  ],
  "preloadedDependencies": [
    {
      "machineName": "H5P.Timer",
      "majorVersion": 0,
      "minorVersion": 4
    },
    {
      "machineName": "EmbeddedJS",
      "majorVersion": 1,
      "minorVersion": 0
    },
    {
      "machineName": "FontAwesome",
      "majorVersion": 4,
      "minorVersion": 5
    },
    {
      "machineName": "H5P.Video",
      "majorVersion": 1,
      "minorVersion": 4
    },
    {
      "machineName": "H5P.JoubelUI",
      "majorVersion": 1,
      "minorVersion": 3
    }
  ],
  "editorDependencies": [
    {
      "machineName": "H5PEditor.RangeList",
      "majorVersion": 1,
      "minorVersion": 0
    },
    {
      "machineName": "H5PEditor.VerticalTabs",
      "majorVersion": 1,
      "minorVersion": 3
    },
    {
      "machineName": "H5PEditor.QuestionSetTextualEditor",
      "majorVersion": 1,
      "minorVersion": 3
    },
    {
      "machineName": "H5PEditor.ShowWhen",
      "majorVersion": 1,
      "minorVersion": 0
    }
  ]
}`

**Comment by otacke** [comment]
### 1 How to load
You're not supposed to modify the libraries directly in sites/default/files/h5p/libraries. That's where they are stored, but they're loaded from cache (as are the stylesheets). So, you'll either have to clear the cache every time you have made changes, or you head over to https://h5p.org/development-environment and familiarize yourself with activating the development mode and using the sites/default/files/h5p/development folder. Everything that H5P finds there will take precedence over libraries in the other folder. After you are done with developing, you could of course update the "real" library files, either directly or by bumping the version number, packing the library and uploading it.


### 2 How to make sure code will not be overwritten
You can't prevent overwriting your custom code if you update existing libraries.

What you are doing is creating a so called fork of the project, and you'd have to bring back your changes after every update. There are several techniques to do that (semi-)automatically, e.g. "patch files" or using "git" to rebase or merge.

Alternatively, you can make the changes and create a pull request - an request to include your changes in the official H5P repository. You'll find more information on that at https://h5p.org/documentation/contributing/contribute-pull-requests


### 3 Why not for time sensitive applications
Using JavaScript in the browser is not a real-time environment. The browser does other stuff in the background and the JavaScript interpreter will do its best to notify you correctly every interval that you requested, but there's no guarantee that it will be exact. It'll be totally fine in the "second(s)" range, but as you go down to milliseconds, it will become more and more unprecise.


### 4 Using this issue for communication
Well, there's contact information at https://github.com/otacke ;-)
